setlocal enabledelayedexpansion
@echo off
set N_GENERATION=3
set GRAMMAR_FILE=cube_thing.txt
set OUTPUT_GRAMMAR_PATH="gram_gen.txt"

::python script part
set PENCIL_SIZE=5
set ANGLE=90

:: Check if build directory exists, create if not
if not exist "build" (
    echo Build directory not found. Creating build directory...
    mkdir build
)

:: build project
cd build
echo -- building project -- 
cmake --build .

:: run the grammar part ( generated by cmake file )
@REM echo --- running run_grammar.bat ---
@REM run_grammar.bat %GRAMMAR_FILE% %N_GENERATION% %OUTPUT_GRAMMAR_PATH% %PENCIL_SIZE% %ANGLE%
@REM cd ..

@REM :: interpret grammar
@REM cd "..\src\Python" 
@REM python interpreter.py %PENCIL_SIZE% %ANGLE% %OUTPUT_GRAMMAR_PATH%
@REM cd "..\..\" 
