setlocal enabledelayedexpansion
@echo off
set N_GENERATION=6
set GRAMMAR_FILE=herb.txt
set OUTPUT_GRAMMAR_PATH="gram_gen.txt"

::python script part
set PENCIL_SIZE=3
set ANGLE=22.5

:: Check if build directory exists, create if not
if not exist "build" (
    echo Build directory not found. Creating build directory...
    mkdir build
)

:: build project
cd build
echo -- building project -- 
cmake --build .

:: run the grammar part ( generated by cmake file )
echo --- running run_grammar.bat ---
run_grammar.bat %GRAMMAR_FILE% %N_GENERATION% %OUTPUT_GRAMMAR_PATH% %PENCIL_SIZE% %ANGLE%
cd ..

:: interpret grammar
echo --- running python interpreter --- 
cd "..\src\Python" 
python interpreter.py %PENCIL_SIZE% %ANGLE% %OUTPUT_GRAMMAR_PATH%
cd "..\..\" 
